### ISSUE TITLE
[Suggestion] Allowing the key to be used on modded doors, could be done with a config file

### ISSUE THREAD

**Issue by Anonyku05** [mt1006/mc-irondoorkey-mod#1]
In the title.

**Comment by mt1006** [comment]
I'll probably add this in the future.

**Comment by mt1006** [comment]
I'll reopen issue to remember

**Comment by mt1006** [comment]
Now it should be possible, add blocks to `#irondoorkey:openable` tag

**Comment by Nova-Katt** [comment]
So how do we do that? The mod doesn't seem to have any configs in modmenu and also doesn't seem to have any commands, or a config-file i can add the blocks to?

**Comment by Anonyku05** [comment]
Must use a Datapack
[Iron_Key_Custom_Blocks.zip](https://github.com/user-attachments/files/16513655/Iron_Key_Custom_Blocks.zip)
Go to the openable.json file in the "_Iron_Key_Custom_Blocks.zip\Iron_Key_Custom_Blocks\data\irondoorkey\tags\blocks_" directory and put your modded doors tag

**Comment by Nova-Katt** [comment]
Didn't get the datapack to work. I did still get the changes to work, but only by going into the jar itself and updating the file in there.
I'm new to datapacks, but have recently started to fiddle with my own personal non-released multi pack, as in.. it changes/adds a few things to already existing stuff.. such as changing/adding recipes to some mods and vanilla items, and also changing tags for two mods.
This one, and Miner's Compass,

Iron Door Key and Miner's Compass seem to have the exact same folder layout with data/namespace/tags/blocks/thefile.json
But neither of these two modifications works in my datapack.
The recipes works, so the datapack itself is setuped correctly when it comes to pack.mcmeta and folder structures. But yeah, I do need some help with the tags.

The files in question are located in:
data/irondoorkey/tags/blocks/openable.json
data/miners-compass/tags/blocks/ore_compass_detectable_blocks.json

I can paste the openable.json code here so you can look at it, and i will also attach the datapack zip incase you want to check the actual files out (with the other modifications in it as well that does indeed work).

{
  "values": [
    "betterend:thallasium_door",
    "betterend:thallasium_trapdoor",
    "betterend:terminite_door",
    "betterend:terminite_trapdoor",
    "ad_astra:steel_door",
    "ad_astra:steel_trapdoor",
    "blockus:obsidian_reinforced_door",
    "blockus:obsidian_reinforced_trapdoor",
    "graveyard:dark_iron_door",
    "graveyard:dark_iron_trapdoor",
    "blockus:iron_gate",
    "blockus:golden_gate"
  ]
}
[NovaAdditions.zip](https://github.com/user-attachments/files/16602389/NovaAdditions.zip)

I can also add that the way I wrote the file in the datapack is exactly the same way I wrote it inside the .jar, and when i change inside the jar it does work, but will ofc be vulnerable to mod updates. And when I then do the same thing in a datapack it just doesn't work.

I am sure that it's me who is missing something somewhere, I just can't figure out what that is since I'm new to writing datapacks, so.. I hope to get some insight here with your help. :)
(I wrote a similar post on Miner's Compass github incase they also know something).
Cheers!

**Comment by mt1006** [comment]
You need to add `"replace": false` line to the JSON:
```
{
  "replace": false,
  "values": [
    "betterend:thallasium_door",
    "betterend:thallasium_trapdoor",
    "betterend:terminite_door",
    "betterend:terminite_trapdoor",
    "ad_astra:steel_door",
    "ad_astra:steel_trapdoor",
    "blockus:obsidian_reinforced_door",
    "blockus:obsidian_reinforced_trapdoor",
    "graveyard:dark_iron_door",
    "graveyard:dark_iron_trapdoor",
    "blockus:iron_gate",
    "blockus:golden_gate"
  ]
}
```

**Comment by Nova-Katt** [comment]
I've tried it like that at first, then tried it both with and without the replace code. No change. :/

**Comment by mt1006** [comment]
I've installed your modpack and it works fine on 1.20.1. What version are you using, and also how exactly do you install your modpack?

**Comment by Nova-Katt** [comment]
The datapack is installed as in the saves/[worldfolder]/datapacks folder as they should.
As you saw in the file there are also modifications to recipes from multiple mods and vanilla minecraft (like craftable spawner and stuff), and they work as they should.
I do run 1.20.4 thou, so maybe there is some difference between 1.20.1 and 1.20.4 that is fiddlydiddly?
I do have the same issue with the other mod thou, Miner's Compass, which is updated for 1.20.4 on the other hand.
It just doesn't want to add the tags to the blocks no matter what I do.

I'll add an example of Miner's Compass since it's the exact same issue there.
I have several ores from multiple mods, where some of them are properly tagged with the #c:ores tag, while some are not.
I have tried to add those ores into the ores.json file i mentioned above in the miners-compass folder.
I have also tried to separate it into it's mod-related folder, such as **data/betterend/tags/blocks/ores.json** where i only add the betterend ores to the c:ores tag, and betternether gets its own folder in the datapack as well, and so on.
I also tried adding a **data/c/tags/blocks/ores.json** with all the ores that needs to get the c:ores tag.
But no matter which option i did, they didn't add the tags to the blocks, so I'm a bit confounded there.

The only reason that Iron Key Door works right now is not because of my datapack, but simply because i modified the actual jar file instead. ^^; (the same did not work for miner's compass)

**Comment by mt1006** [comment]
Ok, I guess I know the issue. First of all, if you're using 1.20.4, that means you're using IronDoorKey 1.0, which doesn't support adding new blocks with tags (it was added in 1.1). As for some tags being tagged and some not, from what I've seen you've mistakenly used dots instead of colons in Miner's Compass JSON, so this might be the issue. Also I would highly recommend using `"replace": false`, as without it, Minecraft removes tags defined by mods or other datapacks, so it can also cause issues.

**Comment by mt1006** [comment]
I'll backport 1.1 to 1.20.4 soon

**Comment by mt1006** [comment]
Or not, now I noticed that IDK 1.1 actually supports 1.20.4

**Comment by mt1006** [comment]
Do you have IronDoorKey 1.0 or 1.1 installed?

**Comment by Nova-Katt** [comment]
I was using 1.1, so at least there is that. :)
Good catch on the . instead of : thou. I had missed that.
While checking for that I noticed it was only 4 ores that had . and that was a few of the ad_astra ores, while the rest had : as they should. But I'm guessing that just since a few of them had dots, the others also didn't work.

I have updated all the files now, the bigger question (miner's compass) is if it will work with just the miners-compass/tags folder, or if i need them split into ad_astra/tags betterend/tags etc, or if i should add them to the simple ores.json in c/tags.
Right now the datapack has all of them, so i guess we'll see if any of those folders will apply the change. :P

**Comment by mt1006** [comment]
It depends whenever the mod is using `#c:` tags. For example in case of Miner's Compass from what I've checked in source code it only uses its `ore_compass_detectable_blocks` tag.

**Comment by Nova-Katt** [comment]
Okay it does work now! So that's great! That means at least some of the files are correct.
Now I can move them out into backup folders to find out if it's the miner's compass, modname or the c folder i should keep, so i don't have triplicates that all add the ore tags. :P 
and the Iron door key part of the datapack also works now!
Those dots.... always something as simple as that. x)
Oh I also noticed that it doesn't like to run the datapacks directly from a zip, i needed to extract it as a folder into the datapack folder to get it working.

world/datapacks/thepack.zip <- didn't work
world/datapacks/thepackfolder <- works

Thank you! :D i've leavered a lot today!

**Comment by Nova-Katt** [comment]
> It depends whenever the mod is using `#c:` tags. For example in case of Miner's Compass from what I've checked in source code it only uses its `ore_compass_detectable_blocks` tag.

Yeah, I did however note that in the default `ore_compass_detectable_blocks` file one of the entries listed was the "#c:ores" tag as an entry. so by adding the c:ores tag to those blocks, miner's compass would pick them up automatically. :D

**Comment by mt1006** [comment]
That's good to hear, as for adding datapack in zip, files need to be placed on the top of the file tree, not inside a directory like you did.
